name: 'Eleos Charity - Checkout Flow'
description: 'A customised checkout flow'
type: 'Commerce'
install:
  - commerce
  - commerce_log
  - commerce_number_pattern
  - commerce_order
  - commerce_store
  - commerce_price
  - commerce_cart
  - commerce_product
  - commerce_shipping
  - commerce_stripe
  - commerce_checkout
config:
  import:
    commerce: '*'
    commerce_log: '*'
    commerce_number_pattern: '*'
    commerce_order: '*'
    commerce_store: '*'
    commerce_price: '*'
    commerce_cart: '*'
    commerce_product: '*'
    commerce_shipping: '*'
    commerce_stripe: '*'
    commerce_checkout: '*'
